//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moves.Net.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Testdata {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Testdata() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moves.Net.UnitTests.Properties.Testdata", typeof(Testdata).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///    &quot;date&quot;: &quot;20130315&quot;,
        ///    &quot;summary&quot;: [
        ///        {
        ///            &quot;activity&quot;: &quot;walking&quot;,
        ///            &quot;group&quot;: &quot;walking&quot;,
        ///            &quot;duration&quot;: 2133,
        ///            &quot;distance&quot;: 1847,
        ///            &quot;steps&quot;: 2500,
        ///            &quot;calories&quot;: 60
        ///        },
        ///        {
        ///            &quot;activity&quot;: &quot;running&quot;,
        ///            &quot;group&quot;: &quot;running&quot;,
        ///            &quot;duration&quot;: 254,
        ///            &quot;distance&quot;: 436,
        ///            &quot;steps&quot;: 624,
        ///            &quot;calories&quot;: 99
        ///        },
        ///        {
        ///            &quot;activity&quot;: &quot;cycling&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SummariesResult {
            get {
                return ResourceManager.GetString("SummariesResult", resourceCulture);
            }
        }
    }
}
